source "https://rubygems.org"

gem "rails", "~> 6.1.0"

gem "bootsnap", ">= 1.4.4", require: false
gem "listen"
gem "sass-rails", ">= 6"
gem "sprockets-rails"

gem "roadie-rails", path: "../../.."

gem "bigdecimal"
gem "mutex_m"
gem "logger"
gem "benchmark"
