source 'https://rubygems.org'

gem 'rails', '~> 6.1.4', '>= 6.1.4.4'

gem 'bootsnap', '>= 1.4.4', require: false
gem 'listen'
gem 'sass-rails', '>= 6'
gem 'sprockets-rails'

gem 'roadie-rails', path: '../../..'
