source 'http://rubygems.org'

gem 'rails', '3.1.11'
gem 'roadie-rails', path: '../../../'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
end

# Use git version of `roadie` until a full release have been made
gem 'roadie', git: 'git://github.com/Mange/roadie.git', branch: 'master'
