source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.0.alpha2"
gem 'sass-rails'
gem 'sprockets-rails'
gem 'roadie-rails', path: '../../..'
