source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false
gem "sass-rails"
gem "sprockets-rails"
gem "roadie-rails", path: "../../.."

gem "bigdecimal"
gem "mutex_m"
gem "logger"
gem "benchmark"
