source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', github: 'rails/rails'
gem 'sass-rails'
gem 'sprockets-rails'
gem 'listen'

gem 'roadie-rails', path: '../../..'
