# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 6.0.0"
gem "sass-rails"
gem "sprockets-rails"
gem "listen"

gem "roadie-rails", path: "../../.."

gem "bigdecimal"
gem "mutex_m"
gem "logger"
gem "benchmark"
