source 'https://rubygems.org'

gem 'rails', '>= 5.0', '< 5.1'
gem 'sqlite3', platforms: :ruby
gem 'activerecord-jdbcsqlite3-adapter', '>= 5.0.pre1', platforms: :jruby
gem 'sass-rails'
gem 'sprockets-rails'

gem 'roadie-rails', path: '../../..'
