name: Main
on:
  push:

jobs:
  base:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6.9", "2.7.2", "3.0.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # This setup is not compatible with the way Travis CI was
      # setup, so the cache will only work for the root folder.
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Rake
        run: rake

      - uses: codecov/codecov-action@v2
